### ISSUE TITLE
Publish chatbot in Teams (obtaining approval of M365 techboard)

### ISSUE THREAD

**Issue by GuillaumeTurcotte** [dto-btn/chatbot#1]
Comply with the AI CoE requirements and provide feedback to MS365 Tech board

**Comment by GuillaumeTurcotte** [comment]
[aia-en-revised.pdf](https://github.com/dto-btn/chatbot/files/11593508/aia-en-revised.pdf)

this is the updated AIA I am sending for review to the AI team

**Comment by GuillaumeTurcotte** [comment]
We are awaiting the final feedback on the revised AIA that is now an Impact level 1 assessment.



[aia-en-revised.pdf](https://github.com/dto-btn/chatbot/files/11737552/aia-en-revised.pdf)

**Comment by GuillaumeTurcotte** [comment]
(this is also a step in obtaining approval by tech board)

**Comment by GuillaumeTurcotte** [comment]
Last email was sent today by @fociera

**Comment by davidsimard2** [comment]
Publish chatbot in Teams - approved.

-----------------------------------------------
Hi Alain, 

This has been approved, you are good to go but please keep us up to date if anything changes in your plan or strategy. I would also ask to include me in the initial phases of the setup as an observer. 

Thank you, 

Youssef Hojeij 
---------------------------------------------------------------------------

**Comment by GuillaumeTurcotte** [comment]
https://github.com/dto-btn/chatbot/issues/9
