### ISSUE TITLE
Prepare Com notes to explain the pilot

### ISSUE THREAD

**Issue by GuillaumeTurcotte** [dto-btn/chatbot#4]
This will need to be posted somewhere on the intranet, and reviewed by comms. 

We will add a URL in the chatbot where we normally have the disclaimer.

* content of the chatbot (indexed material, etc.)
* form to feedback for users
* valid legal disclaimer.

**Comment by GuillaumeTurcotte** [comment]
Here is an example of what Bing does with chatgpt4



![Image](https://github.com/dto-btn/chatbot/assets/78774/9cd66db8-b6dc-4490-9dc7-e74ca538d6b3)

**Comment by davidsimard2** [comment]
Working with Comms 

![Image](https://github.com/dto-btn/chatbot/assets/135240227/4816e56c-a9ed-452f-9a7f-316ba2626d3f)

**Comment by davidsimard2** [comment]
Consultant Meagan McCorkle from Comms is assigned to our team.
